# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackcatPackage',
            fields=[
                ('query_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('login_date', models.DateTimeField(verbose_name='login date')),
                ('establishment', models.CharField(max_length=255)),
            ],
        ),
    ]
