# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinesePackage',
            fields=[
                ('chinese_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('login_date', models.DateTimeField(verbose_name='login date')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='blackcatpackage',
            old_name='query_id',
            new_name='blakcat_id',
        ),
    ]
