# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20170111_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradePackage',
            fields=[
                ('query_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('blackcat_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.BlackcatPackage')),
                ('chinese_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.ChinesePackage')),
            ],
        ),
    ]
