# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20170206_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcatpackage',
            name='establishment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blackcatpackage',
            name='login_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='login date'),
        ),
        migrations.AlterField(
            model_name='blackcatpackage',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinesepackage',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinesepackage',
            name='login_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='login date'),
        ),
        migrations.AlterField(
            model_name='chinesepackage',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
